services:
  - type: web
    name: nginx
    env: docker
    dockerfilePath: ./nginx/Dockerfile
    context: ./nginx
    plan: free
    startCommand: ""  # nginx usa el comando por defecto
    ports:
      - 80

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./padel-intelligence/Dockerfile
    context: ./padel-intelligence
    plan: free
    startCommand: "npm start"
    ports:
      - 3000

  - type: web
    name: backend
    env: docker
    dockerfilePath: ./PadelMatchPredictor/Dockerfile
    context: ./PadelMatchPredictor
    plan: free
    startCommand: "uvicorn main-connected:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: PadelIntelligence1

  - type: privateService
    name: db
    env: docker
    image: postgres:15
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: PadelIntelligence1
      - key: POSTGRES_DB
        value: postgres
