services:
  - type: web
    name: nginx
    env: docker
    dockerfilePath: ./nginx/Dockerfile
    plan: free

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./padel-intelligence/Dockerfile
    plan: free

  - type: web
    name: backend
    env: docker
    dockerfilePath: ./PadelMatchPredictor/Dockerfile
    plan: free

  - type: web
    name: db
    env: docker
    dockerfilePath: ./postgres/Dockerfile
    plan: free
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: PadelIntelligence1
      - key: POSTGRES_DB
        value: postgres
