services:
  - type: web
    name: nginx
    env: docker
    dockerfilePath: ./nginx/Dockerfile
    plan: free
    startCommand: ""
    build:
      context: ./nginx
    ports:
      - port: 80

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./padel-intelligence/Dockerfile
    plan: free
    startCommand: "npm start"
    build:
      context: ./padel-intelligence
    ports:
      - port: 3000

  - type: web
    name: backend
    env: docker
    dockerfilePath: ./PadelMatchPredictor/Dockerfile
    plan: free
    startCommand: "uvicorn main-connected:app --host 0.0.0.0 --port 8000"
    build:
      context: ./PadelMatchPredictor
    ports:
      - port: 8000
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: PadelIntelligence1

  - type: pserv
    name: db
    env: docker
    image:
      name: postgres:15
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: PadelIntelligence1
      - key: POSTGRES_DB
        value: postgres
