services:
  - type: pserv
    name: db
    env: docker
    dockerfilePath: ./db/Dockerfile
    context: ./db
    plan: free
    autoDeploy: true
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: PadelIntelligence1
      - key: POSTGRES_DB
        value: postgres
    disk:
      name: db_data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

  - type: web
    name: backend
    env: docker
    dockerfilePath: ./PadelMatchPredictor/Dockerfile
    context: ./PadelMatchPredictor
    buildCommand: ""
    startCommand: "uvicorn main-connected:app --host 0.0.0.0 --port 8000"
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: PadelIntelligence1

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./padel-intelligence/Dockerfile
    context: ./padel-intelligence
    buildCommand: ""
    startCommand: "npm start"
    plan: free
    autoDeploy: true

  - type: web
    name: nginx
    env: docker
    dockerfilePath: ./nginx/Dockerfile
    context: ./nginx
    buildCommand: ""
    startCommand: ""
    plan: free
    autoDeploy: true
